basePath: /api
definitions:
  models.Conference:
    properties:
      division:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
  models.Team:
    properties:
      conference_id:
        type: integer
      conference_name:
        type: string
      conference_url:
        type: string
      division:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
  responses.HealthCheckResponse:
    properties:
      message:
        type: string
    type: object
  responses.VersionResponse:
    properties:
      version:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: omar.crosby@gmail.com
    name: Omar Crosby
  description: This is a simple API providing access to data from TopDrawerSoccer.
  title: TopDrawerSoccer API
  version: "1.0"
paths:
  /v2/conferences:
    get:
      consumes:
      - application/json
      description: Get a list of conferences
      produces:
      - application/json
      responses: {}
      summary: Get a list of conferences
      tags:
      - Conferences
  /v2/conferences/:division:
    get:
      consumes:
      - application/json
      description: Get a list of conferences
      parameters:
      - default: all
        description: Specify a division you are interested in
        enum:
        - all
        - di
        - dii
        - diii
        - naia
        - njcaa
        in: query
        name: division
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Conference'
            type: array
      summary: Get a list of conferences
      tags:
      - Conferences
  /v2/health:
    get:
      consumes:
      - application/json
      description: Check if the API is up and running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.HealthCheckResponse'
      summary: Health Check
      tags:
      - Admin
  /v2/teams:
    get:
      consumes:
      - application/json
      description: Get all teams
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Team'
            type: array
      summary: Get all teams
      tags:
      - Teams
  /v2/version:
    get:
      consumes:
      - application/json
      description: Get the current version of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.VersionResponse'
      summary: Get the API's current version
      tags:
      - Admin
swagger: "2.0"
