# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  workflow_dispatch: null

  push:
    branches:
      - '**'

env:
  GO_VERSION: 1.21

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          go install go.uber.org/mock/mockgen@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Generate Mocks
        run: |
          pwd
          ls
          go generate ./...

      - name: Lint
        run: |
          pwd
          ls
          golangci-lint run ./...

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          pwd
          ls          
          go install go.uber.org/mock/mockgen@latest
          go install github.com/jstemmer/go-junit-report@latest
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Generate Mocks
        run: go generate ./...

      - name: Test
        run: ginkgo --junit-report=junit.xml ./...

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/junit.xml'
          fail_on_failure: true
          require_tests: true
          annotate_notice: false
          detailed_summary: false

  Build:
    needs: [Analyze, Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          go mod download

      - name: Build
        run: make build

  Release:
    needs: [Build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Semantic Release CLI
        run: |
          npm install -g semantic-release-cli

      - name: Set Git User
        run: |
          git config --global user.email "omar.crosby@gmail.com"
          git config --global user.name "Omar Crosby"

      - name: Run Semantic Release
        run: |
          semantic-release-cli setup
          semantic-release-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Version in VERSION file
        run: bash scripts/update_version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Version in main.go file
        run: bash scripts/update_version_main.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
